apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.fullname" . }}-credentials
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.gateway.accessKey | quote }}
  secretKey: {{ .Values.gateway.secretKey | quote }}
