apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: s3
      port: {{ .Values.gateway.service.port }}
      targetPort: s3
      protocol: TCP
    - name: admin
      port: {{ .Values.gateway.service.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
