// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: keyunwrap.proto

package keyunwrap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyUnwrapService_UnwrapKey_FullMethodName = "/nexus.keyunwrap.KeyUnwrapService/UnwrapKey"
	KeyUnwrapService_Health_FullMethodName    = "/nexus.keyunwrap.KeyUnwrapService/Health"
)

// KeyUnwrapServiceClient is the client API for KeyUnwrapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyUnwrapServiceClient interface {
	// Unwrap an encrypted DEK
	// Returns ECDH-encrypted DEK for DecryptService
	UnwrapKey(ctx context.Context, in *UnwrapKeyRequest, opts ...grpc.CallOption) (*UnwrapKeyResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type keyUnwrapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyUnwrapServiceClient(cc grpc.ClientConnInterface) KeyUnwrapServiceClient {
	return &keyUnwrapServiceClient{cc}
}

func (c *keyUnwrapServiceClient) UnwrapKey(ctx context.Context, in *UnwrapKeyRequest, opts ...grpc.CallOption) (*UnwrapKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnwrapKeyResponse)
	err := c.cc.Invoke(ctx, KeyUnwrapService_UnwrapKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyUnwrapServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, KeyUnwrapService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyUnwrapServiceServer is the server API for KeyUnwrapService service.
// All implementations must embed UnimplementedKeyUnwrapServiceServer
// for forward compatibility.
type KeyUnwrapServiceServer interface {
	// Unwrap an encrypted DEK
	// Returns ECDH-encrypted DEK for DecryptService
	UnwrapKey(context.Context, *UnwrapKeyRequest) (*UnwrapKeyResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedKeyUnwrapServiceServer()
}

// UnimplementedKeyUnwrapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyUnwrapServiceServer struct{}

func (UnimplementedKeyUnwrapServiceServer) UnwrapKey(context.Context, *UnwrapKeyRequest) (*UnwrapKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnwrapKey not implemented")
}
func (UnimplementedKeyUnwrapServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKeyUnwrapServiceServer) mustEmbedUnimplementedKeyUnwrapServiceServer() {}
func (UnimplementedKeyUnwrapServiceServer) testEmbeddedByValue()                          {}

// UnsafeKeyUnwrapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyUnwrapServiceServer will
// result in compilation errors.
type UnsafeKeyUnwrapServiceServer interface {
	mustEmbedUnimplementedKeyUnwrapServiceServer()
}

func RegisterKeyUnwrapServiceServer(s grpc.ServiceRegistrar, srv KeyUnwrapServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyUnwrapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyUnwrapService_ServiceDesc, srv)
}

func _KeyUnwrapService_UnwrapKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnwrapKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyUnwrapServiceServer).UnwrapKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyUnwrapService_UnwrapKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyUnwrapServiceServer).UnwrapKey(ctx, req.(*UnwrapKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyUnwrapService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyUnwrapServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyUnwrapService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyUnwrapServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyUnwrapService_ServiceDesc is the grpc.ServiceDesc for KeyUnwrapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyUnwrapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.keyunwrap.KeyUnwrapService",
	HandlerType: (*KeyUnwrapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnwrapKey",
			Handler:    _KeyUnwrapService_UnwrapKey_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _KeyUnwrapService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyunwrap.proto",
}
