// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: keyunwrap.proto

package keyunwrap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "nexus/proto/common"
	_ "nexus/proto/token"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnwrapKeyRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *common.DelegationToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                        // Must be READ token
	EncryptedDek  *common.EncryptedDEK    `protobuf:"bytes,2,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"`      // From KeyStore
	ClientEcdhPub *common.ECDHPublicKey   `protobuf:"bytes,3,opt,name=client_ecdh_pub,json=clientEcdhPub,proto3" json:"client_ecdh_pub,omitempty"` // Client's ECDH public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapKeyRequest) Reset() {
	*x = UnwrapKeyRequest{}
	mi := &file_keyunwrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapKeyRequest) ProtoMessage() {}

func (x *UnwrapKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyunwrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapKeyRequest.ProtoReflect.Descriptor instead.
func (*UnwrapKeyRequest) Descriptor() ([]byte, []int) {
	return file_keyunwrap_proto_rawDescGZIP(), []int{0}
}

func (x *UnwrapKeyRequest) GetToken() *common.DelegationToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *UnwrapKeyRequest) GetEncryptedDek() *common.EncryptedDEK {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *UnwrapKeyRequest) GetClientEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ClientEcdhPub
	}
	return nil
}

type UnwrapKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEK encrypted with ECDH-derived session key (for DecryptService)
	EcdhEncryptedDek *common.ECDHEncryptedDEK `protobuf:"bytes,1,opt,name=ecdh_encrypted_dek,json=ecdhEncryptedDek,proto3" json:"ecdh_encrypted_dek,omitempty"`
	// Service's ephemeral ECDH public key
	ServiceEcdhPub *common.ECDHPublicKey `protobuf:"bytes,2,opt,name=service_ecdh_pub,json=serviceEcdhPub,proto3" json:"service_ecdh_pub,omitempty"`
	Error          *common.Error         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnwrapKeyResponse) Reset() {
	*x = UnwrapKeyResponse{}
	mi := &file_keyunwrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapKeyResponse) ProtoMessage() {}

func (x *UnwrapKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyunwrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapKeyResponse.ProtoReflect.Descriptor instead.
func (*UnwrapKeyResponse) Descriptor() ([]byte, []int) {
	return file_keyunwrap_proto_rawDescGZIP(), []int{1}
}

func (x *UnwrapKeyResponse) GetEcdhEncryptedDek() *common.ECDHEncryptedDEK {
	if x != nil {
		return x.EcdhEncryptedDek
	}
	return nil
}

func (x *UnwrapKeyResponse) GetServiceEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ServiceEcdhPub
	}
	return nil
}

func (x *UnwrapKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_keyunwrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyunwrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_keyunwrap_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_keyunwrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyunwrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_keyunwrap_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_keyunwrap_proto protoreflect.FileDescriptor

const file_keyunwrap_proto_rawDesc = "" +
	"\n" +
	"\x0fkeyunwrap.proto\x12\x0fnexus.keyunwrap\x1a\fcommon.proto\x1a\vtoken.proto\"\xcd\x01\n" +
	"\x10UnwrapKeyRequest\x123\n" +
	"\x05token\x18\x01 \x01(\v2\x1d.nexus.common.DelegationTokenR\x05token\x12?\n" +
	"\rencrypted_dek\x18\x02 \x01(\v2\x1a.nexus.common.EncryptedDEKR\fencryptedDek\x12C\n" +
	"\x0fclient_ecdh_pub\x18\x03 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\rclientEcdhPub\"\xd3\x01\n" +
	"\x11UnwrapKeyResponse\x12L\n" +
	"\x12ecdh_encrypted_dek\x18\x01 \x01(\v2\x1e.nexus.common.ECDHEncryptedDEKR\x10ecdhEncryptedDek\x12E\n" +
	"\x10service_ecdh_pub\x18\x02 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\x0eserviceEcdhPub\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\xb1\x01\n" +
	"\x10KeyUnwrapService\x12R\n" +
	"\tUnwrapKey\x12!.nexus.keyunwrap.UnwrapKeyRequest\x1a\".nexus.keyunwrap.UnwrapKeyResponse\x12I\n" +
	"\x06Health\x12\x1e.nexus.keyunwrap.HealthRequest\x1a\x1f.nexus.keyunwrap.HealthResponseB\x17Z\x15nexus/proto/keyunwrapb\x06proto3"

var (
	file_keyunwrap_proto_rawDescOnce sync.Once
	file_keyunwrap_proto_rawDescData []byte
)

func file_keyunwrap_proto_rawDescGZIP() []byte {
	file_keyunwrap_proto_rawDescOnce.Do(func() {
		file_keyunwrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyunwrap_proto_rawDesc), len(file_keyunwrap_proto_rawDesc)))
	})
	return file_keyunwrap_proto_rawDescData
}

var file_keyunwrap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_keyunwrap_proto_goTypes = []any{
	(*UnwrapKeyRequest)(nil),        // 0: nexus.keyunwrap.UnwrapKeyRequest
	(*UnwrapKeyResponse)(nil),       // 1: nexus.keyunwrap.UnwrapKeyResponse
	(*HealthRequest)(nil),           // 2: nexus.keyunwrap.HealthRequest
	(*HealthResponse)(nil),          // 3: nexus.keyunwrap.HealthResponse
	(*common.DelegationToken)(nil),  // 4: nexus.common.DelegationToken
	(*common.EncryptedDEK)(nil),     // 5: nexus.common.EncryptedDEK
	(*common.ECDHPublicKey)(nil),    // 6: nexus.common.ECDHPublicKey
	(*common.ECDHEncryptedDEK)(nil), // 7: nexus.common.ECDHEncryptedDEK
	(*common.Error)(nil),            // 8: nexus.common.Error
}
var file_keyunwrap_proto_depIdxs = []int32{
	4, // 0: nexus.keyunwrap.UnwrapKeyRequest.token:type_name -> nexus.common.DelegationToken
	5, // 1: nexus.keyunwrap.UnwrapKeyRequest.encrypted_dek:type_name -> nexus.common.EncryptedDEK
	6, // 2: nexus.keyunwrap.UnwrapKeyRequest.client_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	7, // 3: nexus.keyunwrap.UnwrapKeyResponse.ecdh_encrypted_dek:type_name -> nexus.common.ECDHEncryptedDEK
	6, // 4: nexus.keyunwrap.UnwrapKeyResponse.service_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	8, // 5: nexus.keyunwrap.UnwrapKeyResponse.error:type_name -> nexus.common.Error
	0, // 6: nexus.keyunwrap.KeyUnwrapService.UnwrapKey:input_type -> nexus.keyunwrap.UnwrapKeyRequest
	2, // 7: nexus.keyunwrap.KeyUnwrapService.Health:input_type -> nexus.keyunwrap.HealthRequest
	1, // 8: nexus.keyunwrap.KeyUnwrapService.UnwrapKey:output_type -> nexus.keyunwrap.UnwrapKeyResponse
	3, // 9: nexus.keyunwrap.KeyUnwrapService.Health:output_type -> nexus.keyunwrap.HealthResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_keyunwrap_proto_init() }
func file_keyunwrap_proto_init() {
	if File_keyunwrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyunwrap_proto_rawDesc), len(file_keyunwrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keyunwrap_proto_goTypes,
		DependencyIndexes: file_keyunwrap_proto_depIdxs,
		MessageInfos:      file_keyunwrap_proto_msgTypes,
	}.Build()
	File_keyunwrap_proto = out.File
	file_keyunwrap_proto_goTypes = nil
	file_keyunwrap_proto_depIdxs = nil
}
