// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sts.proto

package sts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssumeRoleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoleArn         string                 `protobuf:"bytes,1,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	RoleSessionName string                 `protobuf:"bytes,2,opt,name=role_session_name,json=roleSessionName,proto3" json:"role_session_name,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ExternalId      string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Policy          string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`                        // JSON policy to scope down permissions
	CallerArn       string                 `protobuf:"bytes,6,opt,name=caller_arn,json=callerArn,proto3" json:"caller_arn,omitempty"` // Set by the gateway
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssumeRoleRequest) Reset() {
	*x = AssumeRoleRequest{}
	mi := &file_sts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssumeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssumeRoleRequest) ProtoMessage() {}

func (x *AssumeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssumeRoleRequest.ProtoReflect.Descriptor instead.
func (*AssumeRoleRequest) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{0}
}

func (x *AssumeRoleRequest) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *AssumeRoleRequest) GetRoleSessionName() string {
	if x != nil {
		return x.RoleSessionName
	}
	return ""
}

func (x *AssumeRoleRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *AssumeRoleRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *AssumeRoleRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *AssumeRoleRequest) GetCallerArn() string {
	if x != nil {
		return x.CallerArn
	}
	return ""
}

type AssumeRoleResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Credentials        *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	AssumedRoleUserArn string                 `protobuf:"bytes,2,opt,name=assumed_role_user_arn,json=assumedRoleUserArn,proto3" json:"assumed_role_user_arn,omitempty"`
	PackedPolicySize   int32                  `protobuf:"varint,3,opt,name=packed_policy_size,json=packedPolicySize,proto3" json:"packed_policy_size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssumeRoleResponse) Reset() {
	*x = AssumeRoleResponse{}
	mi := &file_sts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssumeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssumeRoleResponse) ProtoMessage() {}

func (x *AssumeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssumeRoleResponse.ProtoReflect.Descriptor instead.
func (*AssumeRoleResponse) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{1}
}

func (x *AssumeRoleResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *AssumeRoleResponse) GetAssumedRoleUserArn() string {
	if x != nil {
		return x.AssumedRoleUserArn
	}
	return ""
}

func (x *AssumeRoleResponse) GetPackedPolicySize() int32 {
	if x != nil {
		return x.PackedPolicySize
	}
	return 0
}

type GetSessionTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds int32                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CallerArn       string                 `protobuf:"bytes,2,opt,name=caller_arn,json=callerArn,proto3" json:"caller_arn,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSessionTokenRequest) Reset() {
	*x = GetSessionTokenRequest{}
	mi := &file_sts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTokenRequest) ProtoMessage() {}

func (x *GetSessionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTokenRequest.ProtoReflect.Descriptor instead.
func (*GetSessionTokenRequest) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionTokenRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *GetSessionTokenRequest) GetCallerArn() string {
	if x != nil {
		return x.CallerArn
	}
	return ""
}

type GetSessionTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTokenResponse) Reset() {
	*x = GetSessionTokenResponse{}
	mi := &file_sts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTokenResponse) ProtoMessage() {}

func (x *GetSessionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTokenResponse.ProtoReflect.Descriptor instead.
func (*GetSessionTokenResponse) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionTokenResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type GetFederationTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Policy          string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	CallerArn       string                 `protobuf:"bytes,4,opt,name=caller_arn,json=callerArn,proto3" json:"caller_arn,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFederationTokenRequest) Reset() {
	*x = GetFederationTokenRequest{}
	mi := &file_sts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFederationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederationTokenRequest) ProtoMessage() {}

func (x *GetFederationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederationTokenRequest.ProtoReflect.Descriptor instead.
func (*GetFederationTokenRequest) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{4}
}

func (x *GetFederationTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFederationTokenRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *GetFederationTokenRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *GetFederationTokenRequest) GetCallerArn() string {
	if x != nil {
		return x.CallerArn
	}
	return ""
}

type GetFederationTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Credentials      *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	FederatedUserArn string                 `protobuf:"bytes,2,opt,name=federated_user_arn,json=federatedUserArn,proto3" json:"federated_user_arn,omitempty"`
	PackedPolicySize int32                  `protobuf:"varint,3,opt,name=packed_policy_size,json=packedPolicySize,proto3" json:"packed_policy_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFederationTokenResponse) Reset() {
	*x = GetFederationTokenResponse{}
	mi := &file_sts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFederationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederationTokenResponse) ProtoMessage() {}

func (x *GetFederationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederationTokenResponse.ProtoReflect.Descriptor instead.
func (*GetFederationTokenResponse) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{5}
}

func (x *GetFederationTokenResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *GetFederationTokenResponse) GetFederatedUserArn() string {
	if x != nil {
		return x.FederatedUserArn
	}
	return ""
}

func (x *GetFederationTokenResponse) GetPackedPolicySize() int32 {
	if x != nil {
		return x.PackedPolicySize
	}
	return 0
}

type Credentials struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpirationUnix  int64                  `protobuf:"varint,4,opt,name=expiration_unix,json=expirationUnix,proto3" json:"expiration_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_sts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_sts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_sts_proto_rawDescGZIP(), []int{6}
}

func (x *Credentials) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *Credentials) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *Credentials) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *Credentials) GetExpirationUnix() int64 {
	if x != nil {
		return x.ExpirationUnix
	}
	return 0
}

var File_sts_proto protoreflect.FileDescriptor

const file_sts_proto_rawDesc = "" +
	"\n" +
	"\tsts.proto\x12\x03sts\"\xdd\x01\n" +
	"\x11AssumeRoleRequest\x12\x19\n" +
	"\brole_arn\x18\x01 \x01(\tR\aroleArn\x12*\n" +
	"\x11role_session_name\x18\x02 \x01(\tR\x0froleSessionName\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x12\x1d\n" +
	"\n" +
	"caller_arn\x18\x06 \x01(\tR\tcallerArn\"\xa9\x01\n" +
	"\x12AssumeRoleResponse\x122\n" +
	"\vcredentials\x18\x01 \x01(\v2\x10.sts.CredentialsR\vcredentials\x121\n" +
	"\x15assumed_role_user_arn\x18\x02 \x01(\tR\x12assumedRoleUserArn\x12,\n" +
	"\x12packed_policy_size\x18\x03 \x01(\x05R\x10packedPolicySize\"b\n" +
	"\x16GetSessionTokenRequest\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x05R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"caller_arn\x18\x02 \x01(\tR\tcallerArn\"M\n" +
	"\x17GetSessionTokenResponse\x122\n" +
	"\vcredentials\x18\x01 \x01(\v2\x10.sts.CredentialsR\vcredentials\"\x91\x01\n" +
	"\x19GetFederationTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x1d\n" +
	"\n" +
	"caller_arn\x18\x04 \x01(\tR\tcallerArn\"\xac\x01\n" +
	"\x1aGetFederationTokenResponse\x122\n" +
	"\vcredentials\x18\x01 \x01(\v2\x10.sts.CredentialsR\vcredentials\x12,\n" +
	"\x12federated_user_arn\x18\x02 \x01(\tR\x10federatedUserArn\x12,\n" +
	"\x12packed_policy_size\x18\x03 \x01(\x05R\x10packedPolicySize\"\xab\x01\n" +
	"\vCredentials\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12'\n" +
	"\x0fexpiration_unix\x18\x04 \x01(\x03R\x0eexpirationUnix2\xf0\x01\n" +
	"\n" +
	"STSService\x12=\n" +
	"\n" +
	"AssumeRole\x12\x16.sts.AssumeRoleRequest\x1a\x17.sts.AssumeRoleResponse\x12L\n" +
	"\x0fGetSessionToken\x12\x1b.sts.GetSessionTokenRequest\x1a\x1c.sts.GetSessionTokenResponse\x12U\n" +
	"\x12GetFederationToken\x12\x1e.sts.GetFederationTokenRequest\x1a\x1f.sts.GetFederationTokenResponseB\x11Z\x0fnexus/proto/stsb\x06proto3"

var (
	file_sts_proto_rawDescOnce sync.Once
	file_sts_proto_rawDescData []byte
)

func file_sts_proto_rawDescGZIP() []byte {
	file_sts_proto_rawDescOnce.Do(func() {
		file_sts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sts_proto_rawDesc), len(file_sts_proto_rawDesc)))
	})
	return file_sts_proto_rawDescData
}

var file_sts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sts_proto_goTypes = []any{
	(*AssumeRoleRequest)(nil),          // 0: sts.AssumeRoleRequest
	(*AssumeRoleResponse)(nil),         // 1: sts.AssumeRoleResponse
	(*GetSessionTokenRequest)(nil),     // 2: sts.GetSessionTokenRequest
	(*GetSessionTokenResponse)(nil),    // 3: sts.GetSessionTokenResponse
	(*GetFederationTokenRequest)(nil),  // 4: sts.GetFederationTokenRequest
	(*GetFederationTokenResponse)(nil), // 5: sts.GetFederationTokenResponse
	(*Credentials)(nil),                // 6: sts.Credentials
}
var file_sts_proto_depIdxs = []int32{
	6, // 0: sts.AssumeRoleResponse.credentials:type_name -> sts.Credentials
	6, // 1: sts.GetSessionTokenResponse.credentials:type_name -> sts.Credentials
	6, // 2: sts.GetFederationTokenResponse.credentials:type_name -> sts.Credentials
	0, // 3: sts.STSService.AssumeRole:input_type -> sts.AssumeRoleRequest
	2, // 4: sts.STSService.GetSessionToken:input_type -> sts.GetSessionTokenRequest
	4, // 5: sts.STSService.GetFederationToken:input_type -> sts.GetFederationTokenRequest
	1, // 6: sts.STSService.AssumeRole:output_type -> sts.AssumeRoleResponse
	3, // 7: sts.STSService.GetSessionToken:output_type -> sts.GetSessionTokenResponse
	5, // 8: sts.STSService.GetFederationToken:output_type -> sts.GetFederationTokenResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sts_proto_init() }
func file_sts_proto_init() {
	if File_sts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sts_proto_rawDesc), len(file_sts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sts_proto_goTypes,
		DependencyIndexes: file_sts_proto_depIdxs,
		MessageInfos:      file_sts_proto_msgTypes,
	}.Build()
	File_sts_proto = out.File
	file_sts_proto_goTypes = nil
	file_sts_proto_depIdxs = nil
}
