// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: sts.proto

package sts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	STSService_AssumeRole_FullMethodName         = "/sts.STSService/AssumeRole"
	STSService_GetSessionToken_FullMethodName    = "/sts.STSService/GetSessionToken"
	STSService_GetFederationToken_FullMethodName = "/sts.STSService/GetFederationToken"
)

// STSServiceClient is the client API for STSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// STS Service - Security Token Service
type STSServiceClient interface {
	// AssumeRole returns temporary credentials for an assumed role
	AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*AssumeRoleResponse, error)
	// GetSessionToken returns temporary credentials for the current user
	GetSessionToken(ctx context.Context, in *GetSessionTokenRequest, opts ...grpc.CallOption) (*GetSessionTokenResponse, error)
	// GetFederationToken returns temporary credentials for a federated user
	GetFederationToken(ctx context.Context, in *GetFederationTokenRequest, opts ...grpc.CallOption) (*GetFederationTokenResponse, error)
}

type sTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSTSServiceClient(cc grpc.ClientConnInterface) STSServiceClient {
	return &sTSServiceClient{cc}
}

func (c *sTSServiceClient) AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*AssumeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssumeRoleResponse)
	err := c.cc.Invoke(ctx, STSService_AssumeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) GetSessionToken(ctx context.Context, in *GetSessionTokenRequest, opts ...grpc.CallOption) (*GetSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionTokenResponse)
	err := c.cc.Invoke(ctx, STSService_GetSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sTSServiceClient) GetFederationToken(ctx context.Context, in *GetFederationTokenRequest, opts ...grpc.CallOption) (*GetFederationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFederationTokenResponse)
	err := c.cc.Invoke(ctx, STSService_GetFederationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// STSServiceServer is the server API for STSService service.
// All implementations must embed UnimplementedSTSServiceServer
// for forward compatibility.
//
// STS Service - Security Token Service
type STSServiceServer interface {
	// AssumeRole returns temporary credentials for an assumed role
	AssumeRole(context.Context, *AssumeRoleRequest) (*AssumeRoleResponse, error)
	// GetSessionToken returns temporary credentials for the current user
	GetSessionToken(context.Context, *GetSessionTokenRequest) (*GetSessionTokenResponse, error)
	// GetFederationToken returns temporary credentials for a federated user
	GetFederationToken(context.Context, *GetFederationTokenRequest) (*GetFederationTokenResponse, error)
	mustEmbedUnimplementedSTSServiceServer()
}

// UnimplementedSTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSTSServiceServer struct{}

func (UnimplementedSTSServiceServer) AssumeRole(context.Context, *AssumeRoleRequest) (*AssumeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssumeRole not implemented")
}
func (UnimplementedSTSServiceServer) GetSessionToken(context.Context, *GetSessionTokenRequest) (*GetSessionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionToken not implemented")
}
func (UnimplementedSTSServiceServer) GetFederationToken(context.Context, *GetFederationTokenRequest) (*GetFederationTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFederationToken not implemented")
}
func (UnimplementedSTSServiceServer) mustEmbedUnimplementedSTSServiceServer() {}
func (UnimplementedSTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeSTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to STSServiceServer will
// result in compilation errors.
type UnsafeSTSServiceServer interface {
	mustEmbedUnimplementedSTSServiceServer()
}

func RegisterSTSServiceServer(s grpc.ServiceRegistrar, srv STSServiceServer) {
	// If the following call panics, it indicates UnimplementedSTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&STSService_ServiceDesc, srv)
}

func _STSService_AssumeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).AssumeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_AssumeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).AssumeRole(ctx, req.(*AssumeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_GetSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).GetSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_GetSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).GetSessionToken(ctx, req.(*GetSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _STSService_GetFederationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFederationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STSServiceServer).GetFederationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STSService_GetFederationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STSServiceServer).GetFederationToken(ctx, req.(*GetFederationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// STSService_ServiceDesc is the grpc.ServiceDesc for STSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var STSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sts.STSService",
	HandlerType: (*STSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssumeRole",
			Handler:    _STSService_AssumeRole_Handler,
		},
		{
			MethodName: "GetSessionToken",
			Handler:    _STSService_GetSessionToken_Handler,
		},
		{
			MethodName: "GetFederationToken",
			Handler:    _STSService_GetFederationToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sts.proto",
}
