// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: keystore.proto

package keystore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "nexus/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreKeyRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Bucket       string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey    string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	EncryptedDek *common.EncryptedDEK   `protobuf:"bytes,3,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"`
	KeyId        string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // Optional, auto-generated if empty
	// Metadata for the key entry
	CreatedAt     int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Algorithm     string `protobuf:"bytes,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	ObjectSize    int64  `protobuf:"varint,7,opt,name=object_size,json=objectSize,proto3" json:"object_size,omitempty"` // Original object size for reference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreKeyRequest) Reset() {
	*x = StoreKeyRequest{}
	mi := &file_keystore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyRequest) ProtoMessage() {}

func (x *StoreKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyRequest.ProtoReflect.Descriptor instead.
func (*StoreKeyRequest) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{0}
}

func (x *StoreKeyRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StoreKeyRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *StoreKeyRequest) GetEncryptedDek() *common.EncryptedDEK {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *StoreKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StoreKeyRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StoreKeyRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StoreKeyRequest) GetObjectSize() int64 {
	if x != nil {
		return x.ObjectSize
	}
	return 0
}

type StoreKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	StoredAt      int64                  `protobuf:"varint,2,opt,name=stored_at,json=storedAt,proto3" json:"stored_at,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreKeyResponse) Reset() {
	*x = StoreKeyResponse{}
	mi := &file_keystore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyResponse) ProtoMessage() {}

func (x *StoreKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyResponse.ProtoReflect.Descriptor instead.
func (*StoreKeyResponse) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{1}
}

func (x *StoreKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StoreKeyResponse) GetStoredAt() int64 {
	if x != nil {
		return x.StoredAt
	}
	return 0
}

func (x *StoreKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // Optional, if empty returns latest version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_keystore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetKeyRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *GetKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedDek  *common.EncryptedDEK   `protobuf:"bytes,1,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Error         *common.Error          `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_keystore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyResponse) GetEncryptedDek() *common.EncryptedDEK {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *GetKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetKeyResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GetKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // Optional, if empty deletes all versions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_keystore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKeyRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DeleteKeyRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *DeleteKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // Number of versions deleted
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_keystore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKeyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteKeyResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"` // Object key prefix filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_keystore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{6}
}

func (x *ListKeysRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListKeysRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListKeysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyEntry            `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_keystore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{7}
}

func (x *ListKeysResponse) GetKeys() []*KeyEntry {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListKeysResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListKeysResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type KeyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEntry) Reset() {
	*x = KeyEntry{}
	mi := &file_keystore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEntry) ProtoMessage() {}

func (x *KeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEntry.ProtoReflect.Descriptor instead.
func (*KeyEntry) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{8}
}

func (x *KeyEntry) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *KeyEntry) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *KeyEntry) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_keystore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName     string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	TotalKeysStored int64                  `protobuf:"varint,5,opt,name=total_keys_stored,json=totalKeysStored,proto3" json:"total_keys_stored,omitempty"` // Statistics
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_keystore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_keystore_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetTotalKeysStored() int64 {
	if x != nil {
		return x.TotalKeysStored
	}
	return 0
}

var File_keystore_proto protoreflect.FileDescriptor

const file_keystore_proto_rawDesc = "" +
	"\n" +
	"\x0ekeystore.proto\x12\x0enexus.keystore\x1a\fcommon.proto\"\xfe\x01\n" +
	"\x0fStoreKeyRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12?\n" +
	"\rencrypted_dek\x18\x03 \x01(\v2\x1a.nexus.common.EncryptedDEKR\fencryptedDek\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\talgorithm\x18\x06 \x01(\tR\talgorithm\x12\x1f\n" +
	"\vobject_size\x18\a \x01(\x03R\n" +
	"objectSize\"q\n" +
	"\x10StoreKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1b\n" +
	"\tstored_at\x18\x02 \x01(\x03R\bstoredAt\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.nexus.common.ErrorR\x05error\"]\n" +
	"\rGetKeyRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"\xd0\x01\n" +
	"\x0eGetKeyResponse\x12?\n" +
	"\rencrypted_dek\x18\x01 \x01(\v2\x1a.nexus.common.EncryptedDEKR\fencryptedDek\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12)\n" +
	"\x05error\x18\x05 \x01(\v2\x13.nexus.common.ErrorR\x05error\"`\n" +
	"\x10DeleteKeyRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"}\n" +
	"\x11DeleteKeyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.nexus.common.ErrorR\x05error\"o\n" +
	"\x0fListKeysRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x8c\x01\n" +
	"\x10ListKeysResponse\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.nexus.keystore.KeyEntryR\x04keys\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.nexus.common.ErrorR\x05error\"}\n" +
	"\bKeyEntry\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"\x0f\n" +
	"\rHealthRequest\"\xba\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12*\n" +
	"\x11total_keys_stored\x18\x05 \x01(\x03R\x0ftotalKeysStored2\x93\x03\n" +
	"\x0fKeyStoreService\x12M\n" +
	"\bStoreKey\x12\x1f.nexus.keystore.StoreKeyRequest\x1a .nexus.keystore.StoreKeyResponse\x12G\n" +
	"\x06GetKey\x12\x1d.nexus.keystore.GetKeyRequest\x1a\x1e.nexus.keystore.GetKeyResponse\x12P\n" +
	"\tDeleteKey\x12 .nexus.keystore.DeleteKeyRequest\x1a!.nexus.keystore.DeleteKeyResponse\x12M\n" +
	"\bListKeys\x12\x1f.nexus.keystore.ListKeysRequest\x1a .nexus.keystore.ListKeysResponse\x12G\n" +
	"\x06Health\x12\x1d.nexus.keystore.HealthRequest\x1a\x1e.nexus.keystore.HealthResponseB\x16Z\x14nexus/proto/keystoreb\x06proto3"

var (
	file_keystore_proto_rawDescOnce sync.Once
	file_keystore_proto_rawDescData []byte
)

func file_keystore_proto_rawDescGZIP() []byte {
	file_keystore_proto_rawDescOnce.Do(func() {
		file_keystore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keystore_proto_rawDesc), len(file_keystore_proto_rawDesc)))
	})
	return file_keystore_proto_rawDescData
}

var file_keystore_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_keystore_proto_goTypes = []any{
	(*StoreKeyRequest)(nil),     // 0: nexus.keystore.StoreKeyRequest
	(*StoreKeyResponse)(nil),    // 1: nexus.keystore.StoreKeyResponse
	(*GetKeyRequest)(nil),       // 2: nexus.keystore.GetKeyRequest
	(*GetKeyResponse)(nil),      // 3: nexus.keystore.GetKeyResponse
	(*DeleteKeyRequest)(nil),    // 4: nexus.keystore.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),   // 5: nexus.keystore.DeleteKeyResponse
	(*ListKeysRequest)(nil),     // 6: nexus.keystore.ListKeysRequest
	(*ListKeysResponse)(nil),    // 7: nexus.keystore.ListKeysResponse
	(*KeyEntry)(nil),            // 8: nexus.keystore.KeyEntry
	(*HealthRequest)(nil),       // 9: nexus.keystore.HealthRequest
	(*HealthResponse)(nil),      // 10: nexus.keystore.HealthResponse
	(*common.EncryptedDEK)(nil), // 11: nexus.common.EncryptedDEK
	(*common.Error)(nil),        // 12: nexus.common.Error
}
var file_keystore_proto_depIdxs = []int32{
	11, // 0: nexus.keystore.StoreKeyRequest.encrypted_dek:type_name -> nexus.common.EncryptedDEK
	12, // 1: nexus.keystore.StoreKeyResponse.error:type_name -> nexus.common.Error
	11, // 2: nexus.keystore.GetKeyResponse.encrypted_dek:type_name -> nexus.common.EncryptedDEK
	12, // 3: nexus.keystore.GetKeyResponse.error:type_name -> nexus.common.Error
	12, // 4: nexus.keystore.DeleteKeyResponse.error:type_name -> nexus.common.Error
	8,  // 5: nexus.keystore.ListKeysResponse.keys:type_name -> nexus.keystore.KeyEntry
	12, // 6: nexus.keystore.ListKeysResponse.error:type_name -> nexus.common.Error
	0,  // 7: nexus.keystore.KeyStoreService.StoreKey:input_type -> nexus.keystore.StoreKeyRequest
	2,  // 8: nexus.keystore.KeyStoreService.GetKey:input_type -> nexus.keystore.GetKeyRequest
	4,  // 9: nexus.keystore.KeyStoreService.DeleteKey:input_type -> nexus.keystore.DeleteKeyRequest
	6,  // 10: nexus.keystore.KeyStoreService.ListKeys:input_type -> nexus.keystore.ListKeysRequest
	9,  // 11: nexus.keystore.KeyStoreService.Health:input_type -> nexus.keystore.HealthRequest
	1,  // 12: nexus.keystore.KeyStoreService.StoreKey:output_type -> nexus.keystore.StoreKeyResponse
	3,  // 13: nexus.keystore.KeyStoreService.GetKey:output_type -> nexus.keystore.GetKeyResponse
	5,  // 14: nexus.keystore.KeyStoreService.DeleteKey:output_type -> nexus.keystore.DeleteKeyResponse
	7,  // 15: nexus.keystore.KeyStoreService.ListKeys:output_type -> nexus.keystore.ListKeysResponse
	10, // 16: nexus.keystore.KeyStoreService.Health:output_type -> nexus.keystore.HealthResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_keystore_proto_init() }
func file_keystore_proto_init() {
	if File_keystore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keystore_proto_rawDesc), len(file_keystore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keystore_proto_goTypes,
		DependencyIndexes: file_keystore_proto_depIdxs,
		MessageInfos:      file_keystore_proto_msgTypes,
	}.Build()
	File_keystore_proto = out.File
	file_keystore_proto_goTypes = nil
	file_keystore_proto_depIdxs = nil
}
