// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: keystore.proto

package keystore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyStoreService_StoreKey_FullMethodName  = "/nexus.keystore.KeyStoreService/StoreKey"
	KeyStoreService_GetKey_FullMethodName    = "/nexus.keystore.KeyStoreService/GetKey"
	KeyStoreService_DeleteKey_FullMethodName = "/nexus.keystore.KeyStoreService/DeleteKey"
	KeyStoreService_ListKeys_FullMethodName  = "/nexus.keystore.KeyStoreService/ListKeys"
	KeyStoreService_Health_FullMethodName    = "/nexus.keystore.KeyStoreService/Health"
)

// KeyStoreServiceClient is the client API for KeyStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyStoreServiceClient interface {
	// Store an encrypted DEK
	StoreKey(ctx context.Context, in *StoreKeyRequest, opts ...grpc.CallOption) (*StoreKeyResponse, error)
	// Retrieve an encrypted DEK
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	// Delete an encrypted DEK
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error)
	// List keys for a bucket
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type keyStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyStoreServiceClient(cc grpc.ClientConnInterface) KeyStoreServiceClient {
	return &keyStoreServiceClient{cc}
}

func (c *keyStoreServiceClient) StoreKey(ctx context.Context, in *StoreKeyRequest, opts ...grpc.CallOption) (*StoreKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreKeyResponse)
	err := c.cc.Invoke(ctx, KeyStoreService_StoreKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyStoreServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KeyStoreService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyStoreServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyResponse)
	err := c.cc.Invoke(ctx, KeyStoreService_DeleteKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyStoreServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, KeyStoreService_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyStoreServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, KeyStoreService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyStoreServiceServer is the server API for KeyStoreService service.
// All implementations must embed UnimplementedKeyStoreServiceServer
// for forward compatibility.
type KeyStoreServiceServer interface {
	// Store an encrypted DEK
	StoreKey(context.Context, *StoreKeyRequest) (*StoreKeyResponse, error)
	// Retrieve an encrypted DEK
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	// Delete an encrypted DEK
	DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error)
	// List keys for a bucket
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedKeyStoreServiceServer()
}

// UnimplementedKeyStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyStoreServiceServer struct{}

func (UnimplementedKeyStoreServiceServer) StoreKey(context.Context, *StoreKeyRequest) (*StoreKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreKey not implemented")
}
func (UnimplementedKeyStoreServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeyStoreServiceServer) DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedKeyStoreServiceServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedKeyStoreServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKeyStoreServiceServer) mustEmbedUnimplementedKeyStoreServiceServer() {}
func (UnimplementedKeyStoreServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyStoreServiceServer will
// result in compilation errors.
type UnsafeKeyStoreServiceServer interface {
	mustEmbedUnimplementedKeyStoreServiceServer()
}

func RegisterKeyStoreServiceServer(s grpc.ServiceRegistrar, srv KeyStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyStoreService_ServiceDesc, srv)
}

func _KeyStoreService_StoreKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyStoreServiceServer).StoreKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyStoreService_StoreKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyStoreServiceServer).StoreKey(ctx, req.(*StoreKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyStoreService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyStoreServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyStoreService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyStoreServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyStoreService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyStoreServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyStoreService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyStoreServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyStoreService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyStoreServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyStoreService_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyStoreServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyStoreService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyStoreServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyStoreService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyStoreServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyStoreService_ServiceDesc is the grpc.ServiceDesc for KeyStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.keystore.KeyStoreService",
	HandlerType: (*KeyStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreKey",
			Handler:    _KeyStoreService_StoreKey_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _KeyStoreService_GetKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _KeyStoreService_DeleteKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _KeyStoreService_ListKeys_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _KeyStoreService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keystore.proto",
}
