// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: decrypt.proto

package decrypt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecryptService_Decrypt_FullMethodName      = "/nexus.decrypt.DecryptService/Decrypt"
	DecryptService_DecryptChunk_FullMethodName = "/nexus.decrypt.DecryptService/DecryptChunk"
	DecryptService_Health_FullMethodName       = "/nexus.decrypt.DecryptService/Health"
)

// DecryptServiceClient is the client API for DecryptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecryptServiceClient interface {
	// Decrypt data stream
	// Uses ECDH-derived session key to decrypt DEK, then decrypts data
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DecryptResponse], error)
	// Decrypt a single chunk (for non-streaming use)
	DecryptChunk(ctx context.Context, in *DecryptChunkRequest, opts ...grpc.CallOption) (*DecryptChunkResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type decryptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecryptServiceClient(cc grpc.ClientConnInterface) DecryptServiceClient {
	return &decryptServiceClient{cc}
}

func (c *decryptServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DecryptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecryptService_ServiceDesc.Streams[0], DecryptService_Decrypt_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecryptRequest, DecryptResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecryptService_DecryptClient = grpc.ServerStreamingClient[DecryptResponse]

func (c *decryptServiceClient) DecryptChunk(ctx context.Context, in *DecryptChunkRequest, opts ...grpc.CallOption) (*DecryptChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptChunkResponse)
	err := c.cc.Invoke(ctx, DecryptService_DecryptChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decryptServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DecryptService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecryptServiceServer is the server API for DecryptService service.
// All implementations must embed UnimplementedDecryptServiceServer
// for forward compatibility.
type DecryptServiceServer interface {
	// Decrypt data stream
	// Uses ECDH-derived session key to decrypt DEK, then decrypts data
	Decrypt(*DecryptRequest, grpc.ServerStreamingServer[DecryptResponse]) error
	// Decrypt a single chunk (for non-streaming use)
	DecryptChunk(context.Context, *DecryptChunkRequest) (*DecryptChunkResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDecryptServiceServer()
}

// UnimplementedDecryptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecryptServiceServer struct{}

func (UnimplementedDecryptServiceServer) Decrypt(*DecryptRequest, grpc.ServerStreamingServer[DecryptResponse]) error {
	return status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedDecryptServiceServer) DecryptChunk(context.Context, *DecryptChunkRequest) (*DecryptChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptChunk not implemented")
}
func (UnimplementedDecryptServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDecryptServiceServer) mustEmbedUnimplementedDecryptServiceServer() {}
func (UnimplementedDecryptServiceServer) testEmbeddedByValue()                        {}

// UnsafeDecryptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecryptServiceServer will
// result in compilation errors.
type UnsafeDecryptServiceServer interface {
	mustEmbedUnimplementedDecryptServiceServer()
}

func RegisterDecryptServiceServer(s grpc.ServiceRegistrar, srv DecryptServiceServer) {
	// If the following call panics, it indicates UnimplementedDecryptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecryptService_ServiceDesc, srv)
}

func _DecryptService_Decrypt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DecryptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecryptServiceServer).Decrypt(m, &grpc.GenericServerStream[DecryptRequest, DecryptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecryptService_DecryptServer = grpc.ServerStreamingServer[DecryptResponse]

func _DecryptService_DecryptChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecryptServiceServer).DecryptChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecryptService_DecryptChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecryptServiceServer).DecryptChunk(ctx, req.(*DecryptChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecryptService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecryptServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecryptService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecryptServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DecryptService_ServiceDesc is the grpc.ServiceDesc for DecryptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecryptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.decrypt.DecryptService",
	HandlerType: (*DecryptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecryptChunk",
			Handler:    _DecryptService_DecryptChunk_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DecryptService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Decrypt",
			Handler:       _DecryptService_Decrypt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "decrypt.proto",
}
