// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: decrypt.proto

package decrypt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "nexus/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEK encrypted with ECDH-derived session key
	EcdhEncryptedDek *common.ECDHEncryptedDEK `protobuf:"bytes,1,opt,name=ecdh_encrypted_dek,json=ecdhEncryptedDek,proto3" json:"ecdh_encrypted_dek,omitempty"`
	// Client's ECDH private key
	ClientEcdhPrivateKey []byte `protobuf:"bytes,2,opt,name=client_ecdh_private_key,json=clientEcdhPrivateKey,proto3" json:"client_ecdh_private_key,omitempty"`
	// Service's ephemeral ECDH public key from KeyUnwrapService
	ServiceEcdhPub *common.ECDHPublicKey `protobuf:"bytes,3,opt,name=service_ecdh_pub,json=serviceEcdhPub,proto3" json:"service_ecdh_pub,omitempty"`
	// Encryption algorithm
	Algorithm string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Associated data for AEAD (optional)
	AssociatedData []byte `protobuf:"bytes,5,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_decrypt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decrypt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_decrypt_proto_rawDescGZIP(), []int{0}
}

func (x *DecryptRequest) GetEcdhEncryptedDek() *common.ECDHEncryptedDEK {
	if x != nil {
		return x.EcdhEncryptedDek
	}
	return nil
}

func (x *DecryptRequest) GetClientEcdhPrivateKey() []byte {
	if x != nil {
		return x.ClientEcdhPrivateKey
	}
	return nil
}

func (x *DecryptRequest) GetServiceEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ServiceEcdhPub
	}
	return nil
}

func (x *DecryptRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *DecryptRequest) GetAssociatedData() []byte {
	if x != nil {
		return x.AssociatedData
	}
	return nil
}

type DecryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Decrypted data chunk
	PlaintextChunk []byte `protobuf:"bytes,1,opt,name=plaintext_chunk,json=plaintextChunk,proto3" json:"plaintext_chunk,omitempty"`
	// Chunk sequence number
	Sequence int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Indicates this is the last chunk
	IsLast        bool          `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Error         *common.Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_decrypt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decrypt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_decrypt_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptResponse) GetPlaintextChunk() []byte {
	if x != nil {
		return x.PlaintextChunk
	}
	return nil
}

func (x *DecryptResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DecryptResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *DecryptResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DecryptChunkRequest struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	EcdhEncryptedDek     *common.ECDHEncryptedDEK `protobuf:"bytes,1,opt,name=ecdh_encrypted_dek,json=ecdhEncryptedDek,proto3" json:"ecdh_encrypted_dek,omitempty"`
	ClientEcdhPrivateKey []byte                   `protobuf:"bytes,2,opt,name=client_ecdh_private_key,json=clientEcdhPrivateKey,proto3" json:"client_ecdh_private_key,omitempty"`
	ServiceEcdhPub       *common.ECDHPublicKey    `protobuf:"bytes,3,opt,name=service_ecdh_pub,json=serviceEcdhPub,proto3" json:"service_ecdh_pub,omitempty"`
	Ciphertext           []byte                   `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce                []byte                   `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AuthTag              []byte                   `protobuf:"bytes,6,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	Algorithm            string                   `protobuf:"bytes,7,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	AssociatedData       []byte                   `protobuf:"bytes,8,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DecryptChunkRequest) Reset() {
	*x = DecryptChunkRequest{}
	mi := &file_decrypt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptChunkRequest) ProtoMessage() {}

func (x *DecryptChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decrypt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptChunkRequest.ProtoReflect.Descriptor instead.
func (*DecryptChunkRequest) Descriptor() ([]byte, []int) {
	return file_decrypt_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptChunkRequest) GetEcdhEncryptedDek() *common.ECDHEncryptedDEK {
	if x != nil {
		return x.EcdhEncryptedDek
	}
	return nil
}

func (x *DecryptChunkRequest) GetClientEcdhPrivateKey() []byte {
	if x != nil {
		return x.ClientEcdhPrivateKey
	}
	return nil
}

func (x *DecryptChunkRequest) GetServiceEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ServiceEcdhPub
	}
	return nil
}

func (x *DecryptChunkRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptChunkRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *DecryptChunkRequest) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *DecryptChunkRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *DecryptChunkRequest) GetAssociatedData() []byte {
	if x != nil {
		return x.AssociatedData
	}
	return nil
}

type DecryptChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptChunkResponse) Reset() {
	*x = DecryptChunkResponse{}
	mi := &file_decrypt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptChunkResponse) ProtoMessage() {}

func (x *DecryptChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decrypt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptChunkResponse.ProtoReflect.Descriptor instead.
func (*DecryptChunkResponse) Descriptor() ([]byte, []int) {
	return file_decrypt_proto_rawDescGZIP(), []int{3}
}

func (x *DecryptChunkResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *DecryptChunkResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_decrypt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decrypt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_decrypt_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_decrypt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decrypt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_decrypt_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_decrypt_proto protoreflect.FileDescriptor

const file_decrypt_proto_rawDesc = "" +
	"\n" +
	"\rdecrypt.proto\x12\rnexus.decrypt\x1a\fcommon.proto\"\xa3\x02\n" +
	"\x0eDecryptRequest\x12L\n" +
	"\x12ecdh_encrypted_dek\x18\x01 \x01(\v2\x1e.nexus.common.ECDHEncryptedDEKR\x10ecdhEncryptedDek\x125\n" +
	"\x17client_ecdh_private_key\x18\x02 \x01(\fR\x14clientEcdhPrivateKey\x12E\n" +
	"\x10service_ecdh_pub\x18\x03 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\x0eserviceEcdhPub\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12'\n" +
	"\x0fassociated_data\x18\x05 \x01(\fR\x0eassociatedData\"\x9a\x01\n" +
	"\x0fDecryptResponse\x12'\n" +
	"\x0fplaintext_chunk\x18\x01 \x01(\fR\x0eplaintextChunk\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\xf9\x02\n" +
	"\x13DecryptChunkRequest\x12L\n" +
	"\x12ecdh_encrypted_dek\x18\x01 \x01(\v2\x1e.nexus.common.ECDHEncryptedDEKR\x10ecdhEncryptedDek\x125\n" +
	"\x17client_ecdh_private_key\x18\x02 \x01(\fR\x14clientEcdhPrivateKey\x12E\n" +
	"\x10service_ecdh_pub\x18\x03 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\x0eserviceEcdhPub\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\x12\x19\n" +
	"\bauth_tag\x18\x06 \x01(\fR\aauthTag\x12\x1c\n" +
	"\talgorithm\x18\a \x01(\tR\talgorithm\x12'\n" +
	"\x0fassociated_data\x18\b \x01(\fR\x0eassociatedData\"_\n" +
	"\x14DecryptChunkResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\xfc\x01\n" +
	"\x0eDecryptService\x12J\n" +
	"\aDecrypt\x12\x1d.nexus.decrypt.DecryptRequest\x1a\x1e.nexus.decrypt.DecryptResponse0\x01\x12W\n" +
	"\fDecryptChunk\x12\".nexus.decrypt.DecryptChunkRequest\x1a#.nexus.decrypt.DecryptChunkResponse\x12E\n" +
	"\x06Health\x12\x1c.nexus.decrypt.HealthRequest\x1a\x1d.nexus.decrypt.HealthResponseB\x15Z\x13nexus/proto/decryptb\x06proto3"

var (
	file_decrypt_proto_rawDescOnce sync.Once
	file_decrypt_proto_rawDescData []byte
)

func file_decrypt_proto_rawDescGZIP() []byte {
	file_decrypt_proto_rawDescOnce.Do(func() {
		file_decrypt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decrypt_proto_rawDesc), len(file_decrypt_proto_rawDesc)))
	})
	return file_decrypt_proto_rawDescData
}

var file_decrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_decrypt_proto_goTypes = []any{
	(*DecryptRequest)(nil),          // 0: nexus.decrypt.DecryptRequest
	(*DecryptResponse)(nil),         // 1: nexus.decrypt.DecryptResponse
	(*DecryptChunkRequest)(nil),     // 2: nexus.decrypt.DecryptChunkRequest
	(*DecryptChunkResponse)(nil),    // 3: nexus.decrypt.DecryptChunkResponse
	(*HealthRequest)(nil),           // 4: nexus.decrypt.HealthRequest
	(*HealthResponse)(nil),          // 5: nexus.decrypt.HealthResponse
	(*common.ECDHEncryptedDEK)(nil), // 6: nexus.common.ECDHEncryptedDEK
	(*common.ECDHPublicKey)(nil),    // 7: nexus.common.ECDHPublicKey
	(*common.Error)(nil),            // 8: nexus.common.Error
}
var file_decrypt_proto_depIdxs = []int32{
	6, // 0: nexus.decrypt.DecryptRequest.ecdh_encrypted_dek:type_name -> nexus.common.ECDHEncryptedDEK
	7, // 1: nexus.decrypt.DecryptRequest.service_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	8, // 2: nexus.decrypt.DecryptResponse.error:type_name -> nexus.common.Error
	6, // 3: nexus.decrypt.DecryptChunkRequest.ecdh_encrypted_dek:type_name -> nexus.common.ECDHEncryptedDEK
	7, // 4: nexus.decrypt.DecryptChunkRequest.service_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	8, // 5: nexus.decrypt.DecryptChunkResponse.error:type_name -> nexus.common.Error
	0, // 6: nexus.decrypt.DecryptService.Decrypt:input_type -> nexus.decrypt.DecryptRequest
	2, // 7: nexus.decrypt.DecryptService.DecryptChunk:input_type -> nexus.decrypt.DecryptChunkRequest
	4, // 8: nexus.decrypt.DecryptService.Health:input_type -> nexus.decrypt.HealthRequest
	1, // 9: nexus.decrypt.DecryptService.Decrypt:output_type -> nexus.decrypt.DecryptResponse
	3, // 10: nexus.decrypt.DecryptService.DecryptChunk:output_type -> nexus.decrypt.DecryptChunkResponse
	5, // 11: nexus.decrypt.DecryptService.Health:output_type -> nexus.decrypt.HealthResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_decrypt_proto_init() }
func file_decrypt_proto_init() {
	if File_decrypt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decrypt_proto_rawDesc), len(file_decrypt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decrypt_proto_goTypes,
		DependencyIndexes: file_decrypt_proto_depIdxs,
		MessageInfos:      file_decrypt_proto_msgTypes,
	}.Build()
	File_decrypt_proto = out.File
	file_decrypt_proto_goTypes = nil
	file_decrypt_proto_depIdxs = nil
}
