// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token types for delegation
type TokenType int32

const (
	TokenType_TOKEN_TYPE_WRITE  TokenType = 0
	TokenType_TOKEN_TYPE_READ   TokenType = 1
	TokenType_TOKEN_TYPE_DELETE TokenType = 2
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_WRITE",
		1: "TOKEN_TYPE_READ",
		2: "TOKEN_TYPE_DELETE",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_WRITE":  0,
		"TOKEN_TYPE_READ":   1,
		"TOKEN_TYPE_DELETE": 2,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Delegation token signed by TokenService
type DelegationToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenType     TokenType              `protobuf:"varint,2,opt,name=token_type,json=tokenType,proto3,enum=nexus.common.TokenType" json:"token_type,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,5,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Expiry        int64                  `protobuf:"varint,6,opt,name=expiry,proto3" json:"expiry,omitempty"`                        // Unix timestamp
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	Operations    []string               `protobuf:"bytes,8,rep,name=operations,proto3" json:"operations,omitempty"`
	ContentHash   string                 `protobuf:"bytes,9,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationToken) Reset() {
	*x = DelegationToken{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationToken) ProtoMessage() {}

func (x *DelegationToken) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationToken.ProtoReflect.Descriptor instead.
func (*DelegationToken) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *DelegationToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *DelegationToken) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_TOKEN_TYPE_WRITE
}

func (x *DelegationToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DelegationToken) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DelegationToken) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *DelegationToken) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *DelegationToken) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DelegationToken) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *DelegationToken) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *DelegationToken) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Encrypted DEK structure
type EncryptedDEK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  []byte                 `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyVersion    int32                  `protobuf:"varint,4,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDEK) Reset() {
	*x = EncryptedDEK{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDEK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDEK) ProtoMessage() {}

func (x *EncryptedDEK) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDEK.ProtoReflect.Descriptor instead.
func (*EncryptedDEK) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedDEK) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *EncryptedDEK) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *EncryptedDEK) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *EncryptedDEK) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

// ECDH public key for key exchange
type ECDHPublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // X9.62 uncompressed point format
	Curve         string                 `protobuf:"bytes,2,opt,name=curve,proto3" json:"curve,omitempty"`                          // e.g., "P-256"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDHPublicKey) Reset() {
	*x = ECDHPublicKey{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDHPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDHPublicKey) ProtoMessage() {}

func (x *ECDHPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDHPublicKey.ProtoReflect.Descriptor instead.
func (*ECDHPublicKey) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ECDHPublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ECDHPublicKey) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

// ECDH encrypted DEK (encrypted with derived shared secret)
type ECDHEncryptedDEK struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext         []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                                             // AES-256-GCM encrypted DEK
	Nonce              []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                       // GCM nonce
	EphemeralPublicKey []byte                 `protobuf:"bytes,3,opt,name=ephemeral_public_key,json=ephemeralPublicKey,proto3" json:"ephemeral_public_key,omitempty"` // Service's ephemeral ECDH public key
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ECDHEncryptedDEK) Reset() {
	*x = ECDHEncryptedDEK{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDHEncryptedDEK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDHEncryptedDEK) ProtoMessage() {}

func (x *ECDHEncryptedDEK) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDHEncryptedDEK.ProtoReflect.Descriptor instead.
func (*ECDHEncryptedDEK) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *ECDHEncryptedDEK) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *ECDHEncryptedDEK) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ECDHEncryptedDEK) GetEphemeralPublicKey() []byte {
	if x != nil {
		return x.EphemeralPublicKey
	}
	return nil
}

// Service metadata for registration
type ServiceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMetadata) Reset() {
	*x = ServiceMetadata{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetadata) ProtoMessage() {}

func (x *ServiceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetadata.ProtoReflect.Descriptor instead.
func (*ServiceMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceMetadata) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceMetadata) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceMetadata) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceMetadata) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ServiceMetadata) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *ServiceMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Health check status
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *HealthStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

// Error response
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\fnexus.common\"\xcc\x02\n" +
	"\x0fDelegationToken\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x126\n" +
	"\n" +
	"token_type\x18\x02 \x01(\x0e2\x17.nexus.common.TokenTypeR\ttokenType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x05 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\x03R\x06expiry\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"operations\x18\b \x03(\tR\n" +
	"operations\x12!\n" +
	"\fcontent_hash\x18\t \x01(\tR\vcontentHash\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\"\x89\x01\n" +
	"\fEncryptedDEK\x12#\n" +
	"\rencrypted_key\x18\x01 \x01(\fR\fencryptedKey\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vkey_version\x18\x04 \x01(\x05R\n" +
	"keyVersion\"D\n" +
	"\rECDHPublicKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05curve\x18\x02 \x01(\tR\x05curve\"z\n" +
	"\x10ECDHEncryptedDEK\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x120\n" +
	"\x14ephemeral_public_key\x18\x03 \x01(\fR\x12ephemeralPublicKey\"\xd4\x01\n" +
	"\x0fServiceMetadata\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"\x80\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\x03R\tcheckedAt\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails*M\n" +
	"\tTokenType\x12\x14\n" +
	"\x10TOKEN_TYPE_WRITE\x10\x00\x12\x13\n" +
	"\x0fTOKEN_TYPE_READ\x10\x01\x12\x15\n" +
	"\x11TOKEN_TYPE_DELETE\x10\x02B\x14Z\x12nexus/proto/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(TokenType)(0),           // 0: nexus.common.TokenType
	(*DelegationToken)(nil),  // 1: nexus.common.DelegationToken
	(*EncryptedDEK)(nil),     // 2: nexus.common.EncryptedDEK
	(*ECDHPublicKey)(nil),    // 3: nexus.common.ECDHPublicKey
	(*ECDHEncryptedDEK)(nil), // 4: nexus.common.ECDHEncryptedDEK
	(*ServiceMetadata)(nil),  // 5: nexus.common.ServiceMetadata
	(*HealthStatus)(nil),     // 6: nexus.common.HealthStatus
	(*Error)(nil),            // 7: nexus.common.Error
}
var file_common_proto_depIdxs = []int32{
	0, // 0: nexus.common.DelegationToken.token_type:type_name -> nexus.common.TokenType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
