// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: encrypt.proto

package encrypt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncryptService_Encrypt_FullMethodName      = "/nexus.encrypt.EncryptService/Encrypt"
	EncryptService_EncryptChunk_FullMethodName = "/nexus.encrypt.EncryptService/EncryptChunk"
	EncryptService_Health_FullMethodName       = "/nexus.encrypt.EncryptService/Health"
)

// EncryptServiceClient is the client API for EncryptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncryptServiceClient interface {
	// Encrypt data stream
	// Uses ECDH-derived session key to decrypt DEK, then encrypts data
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptResponse], error)
	// Encrypt a single chunk (for non-streaming use)
	EncryptChunk(ctx context.Context, in *EncryptChunkRequest, opts ...grpc.CallOption) (*EncryptChunkResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type encryptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptServiceClient(cc grpc.ClientConnInterface) EncryptServiceClient {
	return &encryptServiceClient{cc}
}

func (c *encryptServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EncryptService_ServiceDesc.Streams[0], EncryptService_Encrypt_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncryptRequest, EncryptResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EncryptService_EncryptClient = grpc.ServerStreamingClient[EncryptResponse]

func (c *encryptServiceClient) EncryptChunk(ctx context.Context, in *EncryptChunkRequest, opts ...grpc.CallOption) (*EncryptChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptChunkResponse)
	err := c.cc.Invoke(ctx, EncryptService_EncryptChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, EncryptService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptServiceServer is the server API for EncryptService service.
// All implementations must embed UnimplementedEncryptServiceServer
// for forward compatibility.
type EncryptServiceServer interface {
	// Encrypt data stream
	// Uses ECDH-derived session key to decrypt DEK, then encrypts data
	Encrypt(*EncryptRequest, grpc.ServerStreamingServer[EncryptResponse]) error
	// Encrypt a single chunk (for non-streaming use)
	EncryptChunk(context.Context, *EncryptChunkRequest) (*EncryptChunkResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedEncryptServiceServer()
}

// UnimplementedEncryptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncryptServiceServer struct{}

func (UnimplementedEncryptServiceServer) Encrypt(*EncryptRequest, grpc.ServerStreamingServer[EncryptResponse]) error {
	return status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedEncryptServiceServer) EncryptChunk(context.Context, *EncryptChunkRequest) (*EncryptChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptChunk not implemented")
}
func (UnimplementedEncryptServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEncryptServiceServer) mustEmbedUnimplementedEncryptServiceServer() {}
func (UnimplementedEncryptServiceServer) testEmbeddedByValue()                        {}

// UnsafeEncryptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptServiceServer will
// result in compilation errors.
type UnsafeEncryptServiceServer interface {
	mustEmbedUnimplementedEncryptServiceServer()
}

func RegisterEncryptServiceServer(s grpc.ServiceRegistrar, srv EncryptServiceServer) {
	// If the following call panics, it indicates UnimplementedEncryptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncryptService_ServiceDesc, srv)
}

func _EncryptService_Encrypt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EncryptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EncryptServiceServer).Encrypt(m, &grpc.GenericServerStream[EncryptRequest, EncryptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EncryptService_EncryptServer = grpc.ServerStreamingServer[EncryptResponse]

func _EncryptService_EncryptChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptServiceServer).EncryptChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptService_EncryptChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptServiceServer).EncryptChunk(ctx, req.(*EncryptChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncryptService_ServiceDesc is the grpc.ServiceDesc for EncryptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncryptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.encrypt.EncryptService",
	HandlerType: (*EncryptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptChunk",
			Handler:    _EncryptService_EncryptChunk_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _EncryptService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Encrypt",
			Handler:       _EncryptService_Encrypt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "encrypt.proto",
}
