// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: encrypt.proto

package encrypt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "nexus/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEK encrypted with ECDH-derived session key
	EcdhEncryptedDek *common.ECDHEncryptedDEK `protobuf:"bytes,1,opt,name=ecdh_encrypted_dek,json=ecdhEncryptedDek,proto3" json:"ecdh_encrypted_dek,omitempty"`
	// Client's ECDH private key (for deriving shared secret)
	// Note: This is passed securely via mTLS channel
	ClientEcdhPrivateKey []byte `protobuf:"bytes,2,opt,name=client_ecdh_private_key,json=clientEcdhPrivateKey,proto3" json:"client_ecdh_private_key,omitempty"`
	// Service's ephemeral ECDH public key from KeyGenService
	ServiceEcdhPub *common.ECDHPublicKey `protobuf:"bytes,3,opt,name=service_ecdh_pub,json=serviceEcdhPub,proto3" json:"service_ecdh_pub,omitempty"`
	// Encryption algorithm
	Algorithm string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // e.g., "AES-256-GCM"
	// Associated data for AEAD (optional)
	AssociatedData []byte `protobuf:"bytes,5,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_encrypt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptRequest) GetEcdhEncryptedDek() *common.ECDHEncryptedDEK {
	if x != nil {
		return x.EcdhEncryptedDek
	}
	return nil
}

func (x *EncryptRequest) GetClientEcdhPrivateKey() []byte {
	if x != nil {
		return x.ClientEcdhPrivateKey
	}
	return nil
}

func (x *EncryptRequest) GetServiceEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ServiceEcdhPub
	}
	return nil
}

func (x *EncryptRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *EncryptRequest) GetAssociatedData() []byte {
	if x != nil {
		return x.AssociatedData
	}
	return nil
}

type EncryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encrypted data chunk
	CiphertextChunk []byte `protobuf:"bytes,1,opt,name=ciphertext_chunk,json=ciphertextChunk,proto3" json:"ciphertext_chunk,omitempty"`
	// Nonce/IV for this chunk (first chunk contains full nonce)
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Authentication tag (last chunk contains final tag)
	AuthTag []byte `protobuf:"bytes,3,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	// Chunk sequence number
	Sequence int64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Indicates this is the last chunk
	IsLast        bool          `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Error         *common.Error `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_encrypt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptResponse) GetCiphertextChunk() []byte {
	if x != nil {
		return x.CiphertextChunk
	}
	return nil
}

func (x *EncryptResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptResponse) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *EncryptResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EncryptResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *EncryptResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type EncryptChunkRequest struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	EcdhEncryptedDek     *common.ECDHEncryptedDEK `protobuf:"bytes,1,opt,name=ecdh_encrypted_dek,json=ecdhEncryptedDek,proto3" json:"ecdh_encrypted_dek,omitempty"`
	ClientEcdhPrivateKey []byte                   `protobuf:"bytes,2,opt,name=client_ecdh_private_key,json=clientEcdhPrivateKey,proto3" json:"client_ecdh_private_key,omitempty"`
	ServiceEcdhPub       *common.ECDHPublicKey    `protobuf:"bytes,3,opt,name=service_ecdh_pub,json=serviceEcdhPub,proto3" json:"service_ecdh_pub,omitempty"`
	Plaintext            []byte                   `protobuf:"bytes,4,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Algorithm            string                   `protobuf:"bytes,5,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	AssociatedData       []byte                   `protobuf:"bytes,6,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EncryptChunkRequest) Reset() {
	*x = EncryptChunkRequest{}
	mi := &file_encrypt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptChunkRequest) ProtoMessage() {}

func (x *EncryptChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptChunkRequest.ProtoReflect.Descriptor instead.
func (*EncryptChunkRequest) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptChunkRequest) GetEcdhEncryptedDek() *common.ECDHEncryptedDEK {
	if x != nil {
		return x.EcdhEncryptedDek
	}
	return nil
}

func (x *EncryptChunkRequest) GetClientEcdhPrivateKey() []byte {
	if x != nil {
		return x.ClientEcdhPrivateKey
	}
	return nil
}

func (x *EncryptChunkRequest) GetServiceEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ServiceEcdhPub
	}
	return nil
}

func (x *EncryptChunkRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *EncryptChunkRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *EncryptChunkRequest) GetAssociatedData() []byte {
	if x != nil {
		return x.AssociatedData
	}
	return nil
}

type EncryptChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AuthTag       []byte                 `protobuf:"bytes,3,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	Error         *common.Error          `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptChunkResponse) Reset() {
	*x = EncryptChunkResponse{}
	mi := &file_encrypt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptChunkResponse) ProtoMessage() {}

func (x *EncryptChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptChunkResponse.ProtoReflect.Descriptor instead.
func (*EncryptChunkResponse) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptChunkResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptChunkResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptChunkResponse) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *EncryptChunkResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_encrypt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_encrypt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_encrypt_proto protoreflect.FileDescriptor

const file_encrypt_proto_rawDesc = "" +
	"\n" +
	"\rencrypt.proto\x12\rnexus.encrypt\x1a\fcommon.proto\"\xa3\x02\n" +
	"\x0eEncryptRequest\x12L\n" +
	"\x12ecdh_encrypted_dek\x18\x01 \x01(\v2\x1e.nexus.common.ECDHEncryptedDEKR\x10ecdhEncryptedDek\x125\n" +
	"\x17client_ecdh_private_key\x18\x02 \x01(\fR\x14clientEcdhPrivateKey\x12E\n" +
	"\x10service_ecdh_pub\x18\x03 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\x0eserviceEcdhPub\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12'\n" +
	"\x0fassociated_data\x18\x05 \x01(\fR\x0eassociatedData\"\xcd\x01\n" +
	"\x0fEncryptResponse\x12)\n" +
	"\x10ciphertext_chunk\x18\x01 \x01(\fR\x0fciphertextChunk\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x19\n" +
	"\bauth_tag\x18\x03 \x01(\fR\aauthTag\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\x12)\n" +
	"\x05error\x18\x06 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\xc6\x02\n" +
	"\x13EncryptChunkRequest\x12L\n" +
	"\x12ecdh_encrypted_dek\x18\x01 \x01(\v2\x1e.nexus.common.ECDHEncryptedDEKR\x10ecdhEncryptedDek\x125\n" +
	"\x17client_ecdh_private_key\x18\x02 \x01(\fR\x14clientEcdhPrivateKey\x12E\n" +
	"\x10service_ecdh_pub\x18\x03 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\x0eserviceEcdhPub\x12\x1c\n" +
	"\tplaintext\x18\x04 \x01(\fR\tplaintext\x12\x1c\n" +
	"\talgorithm\x18\x05 \x01(\tR\talgorithm\x12'\n" +
	"\x0fassociated_data\x18\x06 \x01(\fR\x0eassociatedData\"\x92\x01\n" +
	"\x14EncryptChunkResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x19\n" +
	"\bauth_tag\x18\x03 \x01(\fR\aauthTag\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\xfc\x01\n" +
	"\x0eEncryptService\x12J\n" +
	"\aEncrypt\x12\x1d.nexus.encrypt.EncryptRequest\x1a\x1e.nexus.encrypt.EncryptResponse0\x01\x12W\n" +
	"\fEncryptChunk\x12\".nexus.encrypt.EncryptChunkRequest\x1a#.nexus.encrypt.EncryptChunkResponse\x12E\n" +
	"\x06Health\x12\x1c.nexus.encrypt.HealthRequest\x1a\x1d.nexus.encrypt.HealthResponseB\x15Z\x13nexus/proto/encryptb\x06proto3"

var (
	file_encrypt_proto_rawDescOnce sync.Once
	file_encrypt_proto_rawDescData []byte
)

func file_encrypt_proto_rawDescGZIP() []byte {
	file_encrypt_proto_rawDescOnce.Do(func() {
		file_encrypt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encrypt_proto_rawDesc), len(file_encrypt_proto_rawDesc)))
	})
	return file_encrypt_proto_rawDescData
}

var file_encrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_encrypt_proto_goTypes = []any{
	(*EncryptRequest)(nil),          // 0: nexus.encrypt.EncryptRequest
	(*EncryptResponse)(nil),         // 1: nexus.encrypt.EncryptResponse
	(*EncryptChunkRequest)(nil),     // 2: nexus.encrypt.EncryptChunkRequest
	(*EncryptChunkResponse)(nil),    // 3: nexus.encrypt.EncryptChunkResponse
	(*HealthRequest)(nil),           // 4: nexus.encrypt.HealthRequest
	(*HealthResponse)(nil),          // 5: nexus.encrypt.HealthResponse
	(*common.ECDHEncryptedDEK)(nil), // 6: nexus.common.ECDHEncryptedDEK
	(*common.ECDHPublicKey)(nil),    // 7: nexus.common.ECDHPublicKey
	(*common.Error)(nil),            // 8: nexus.common.Error
}
var file_encrypt_proto_depIdxs = []int32{
	6, // 0: nexus.encrypt.EncryptRequest.ecdh_encrypted_dek:type_name -> nexus.common.ECDHEncryptedDEK
	7, // 1: nexus.encrypt.EncryptRequest.service_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	8, // 2: nexus.encrypt.EncryptResponse.error:type_name -> nexus.common.Error
	6, // 3: nexus.encrypt.EncryptChunkRequest.ecdh_encrypted_dek:type_name -> nexus.common.ECDHEncryptedDEK
	7, // 4: nexus.encrypt.EncryptChunkRequest.service_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	8, // 5: nexus.encrypt.EncryptChunkResponse.error:type_name -> nexus.common.Error
	0, // 6: nexus.encrypt.EncryptService.Encrypt:input_type -> nexus.encrypt.EncryptRequest
	2, // 7: nexus.encrypt.EncryptService.EncryptChunk:input_type -> nexus.encrypt.EncryptChunkRequest
	4, // 8: nexus.encrypt.EncryptService.Health:input_type -> nexus.encrypt.HealthRequest
	1, // 9: nexus.encrypt.EncryptService.Encrypt:output_type -> nexus.encrypt.EncryptResponse
	3, // 10: nexus.encrypt.EncryptService.EncryptChunk:output_type -> nexus.encrypt.EncryptChunkResponse
	5, // 11: nexus.encrypt.EncryptService.Health:output_type -> nexus.encrypt.HealthResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_encrypt_proto_init() }
func file_encrypt_proto_init() {
	if File_encrypt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encrypt_proto_rawDesc), len(file_encrypt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encrypt_proto_goTypes,
		DependencyIndexes: file_encrypt_proto_depIdxs,
		MessageInfos:      file_encrypt_proto_msgTypes,
	}.Build()
	File_encrypt_proto = out.File
	file_encrypt_proto_goTypes = nil
	file_encrypt_proto_depIdxs = nil
}
