package keyunwrap_service

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdh"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sync"
	"time"

	"golang.org/x/crypto/hkdf"
	"go.uber.org/zap"

	"nexus/internal/services"
)

// KeyUnwrapService unwraps (decrypts) data encryption keys
// Uses private key (SK_Decrypt) to decrypt encrypted DEK
// Cannot encrypt - only has private key
type KeyUnwrapService struct {
	mu              sync.RWMutex
	decryptPrivKey  *ecdsa.PrivateKey   // Long-term private key for decrypting DEK
	keyID           string
	keyPath         string
	curve           elliptic.Curve
	auditLog        *AuditLogger
}

// AuditLogger for keyunwrap service
type AuditLogger struct {
	mu      sync.RWMutex
	entries []AuditEntry
	maxSize int
}

type AuditEntry struct {
	Timestamp time.Time
	Operation string
	KeyID     string
	TokenID   string
	UserID    string
	Bucket    string
	ObjectKey string
	Result    string
}

// KeyUnwrapServiceConfig configuration
type KeyUnwrapServiceConfig struct {
	KeyPath   string // Path to load private key
	KeyID     string // Optional key identifier
	AuditSize int    // Max audit entries
}

// NewKeyUnwrapService creates a new key unwrap service
func NewKeyUnwrapService(cfg KeyUnwrapServiceConfig) (*KeyUnwrapService, error) {
	var privKey *ecdsa.PrivateKey
	var keyID string

	// Try to load existing private key
	if cfg.KeyPath != "" {
		privKeyPath := cfg.KeyPath + ".priv"
		keyData, err := os.ReadFile(privKeyPath)
		if err == nil {
			privKey, err = x509.ParseECPrivateKey(keyData)
			if err == nil {
				zap.L().Info("loaded existing private key", zap.String("path", privKeyPath))
			}
		}
	}

	// If no private key loaded, this is an error - KeyUnwrapService needs the private key
	// The private key should have been generated by KeyGenService
	if privKey == nil {
		// Generate a new key pair if no key exists (for initial setup)
		privKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			return nil, fmt.Errorf("failed to generate key pair: %w", err)
		}

		// Save keys if path provided
		if cfg.KeyPath != "" {
			dir := filepath.Dir(cfg.KeyPath)
			if err := os.MkdirAll(dir, 0700); err != nil {
				return nil, fmt.Errorf("failed to create key directory: %w", err)
			}

			// Save private key
			privKeyBytes, err := x509.MarshalECPrivateKey(privKey)
			if err != nil {
				return nil, fmt.Errorf("failed to marshal private key: %w", err)
			}
			privKeyPath := cfg.KeyPath + ".priv"
			if err := os.WriteFile(privKeyPath, privKeyBytes, 0600); err != nil {
				return nil, fmt.Errorf("failed to save private key: %w", err)
			}

			// Save public key
			pubKeyBytes, err := x509.MarshalPKIXPublicKey(&privKey.PublicKey)
			if err != nil {
				return nil, fmt.Errorf("failed to marshal public key: %w", err)
			}
			pubKeyPath := cfg.KeyPath + ".pub"
			if err := os.WriteFile(pubKeyPath, pubKeyBytes, 0644); err != nil {
				return nil, fmt.Errorf("failed to save public key: %w", err)
			}

			zap.L().Info("generated and saved key pair for KeyUnwrapService",
				zap.String("priv_path", privKeyPath),
				zap.String("pub_path", pubKeyPath))
		}
	}

	// Generate key ID
	if cfg.KeyID != "" {
		keyID = cfg.KeyID
	} else {
		keyIDBytes := make([]byte, 16)
		rand.Read(keyIDBytes)
		keyID = base64.URLEncoding.EncodeToString(keyIDBytes)
	}

	auditSize := cfg.AuditSize
	if auditSize <= 0 {
		auditSize = 10000
	}

	return &KeyUnwrapService{
		decryptPrivKey: privKey,
		keyID:          keyID,
		keyPath:        cfg.KeyPath,
		curve:          privKey.Curve,
		auditLog: &AuditLogger{
			entries: make([]AuditEntry, 0, auditSize),
			maxSize: auditSize,
		},
	}, nil
}

// UnwrapKey decrypts an encrypted DEK and returns it encrypted with session key
func (k *KeyUnwrapService) UnwrapKey(ctx context.Context, tokenID, userID, bucket, objectKey string, encryptedDEK *services.EncryptedDEK, clientECDHPub *services.ECDHPublicKey) (*services.ECDHEncryptedDEK, *services.ECDHPublicKey, error) {
	// Decrypt DEK using private key (ECIES)
	dek, err := k.decryptDEKWithPrivateKey(encryptedDEK.EncryptedKey)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to decrypt DEK: %w", err)
	}

	// Generate ephemeral ECDH key pair for session
	ephemeralPriv, err := ecdh.P256().GenerateKey(rand.Reader)
	if err != nil {
		clearBytes(dek)
		return nil, nil, fmt.Errorf("failed to generate ephemeral ECDH key: %w", err)
	}
	ephemeralPub := ephemeralPriv.PublicKey()

	// Parse client's ECDH public key
	clientPub, err := ecdh.P256().NewPublicKey(clientECDHPub.PublicKey)
	if err != nil {
		clearBytes(dek)
		return nil, nil, fmt.Errorf("failed to parse client ECDH public key: %w", err)
	}

	// Derive shared secret using ECDH
	sharedSecret, err := ephemeralPriv.ECDH(clientPub)
	if err != nil {
		clearBytes(dek)
		return nil, nil, fmt.Errorf("failed to derive shared secret: %w", err)
	}

	// Derive AES key from shared secret using HKDF
	sessionKey := k.deriveSessionKey(sharedSecret, ephemeralPub.Bytes(), clientPub.Bytes())

	// Encrypt DEK with session key
	ecdhEncryptedDEK, err := k.encryptDEKWithSessionKey(dek, sessionKey)
	if err != nil {
		clearBytes(dek)
		clearBytes(sessionKey)
		clearBytes(sharedSecret)
		return nil, nil, fmt.Errorf("failed to encrypt DEK with session key: %w", err)
	}

	// Clear sensitive data
	clearBytes(dek)
	clearBytes(sessionKey)
	clearBytes(sharedSecret)

	// Log audit
	k.logAudit("unwrap", encryptedDEK.KeyID, tokenID, userID, bucket, objectKey, "success")

	zap.L().Info("key unwrapped",
		zap.String("key_id", encryptedDEK.KeyID),
		zap.String("token_id", tokenID),
		zap.String("bucket", bucket))

	return ecdhEncryptedDEK, &services.ECDHPublicKey{
		PublicKey: ephemeralPub.Bytes(),
		Curve:     "P-256",
	}, nil
}

// decryptDEKWithPrivateKey decrypts DEK using ECIES
func (k *KeyUnwrapService) decryptDEKWithPrivateKey(encryptedKey []byte) ([]byte, error) {
	k.mu.RLock()
	privKey := k.decryptPrivKey
	k.mu.RUnlock()

	// ECIES decryption:
	// Format: ephemeral_pub (65 bytes for P256 uncompressed) || nonce (12 bytes) || ciphertext

	// Parse ephemeral public key
	pubKeyLen := 65 // P-256 uncompressed point
	if len(encryptedKey) < pubKeyLen {
		return nil, fmt.Errorf("invalid encrypted key format: too short")
	}

	ephemeralPubBytes := encryptedKey[:pubKeyLen]
	ephemeralPubX, ephemeralPubY := elliptic.Unmarshal(k.curve, ephemeralPubBytes)
	if ephemeralPubX == nil {
		return nil, fmt.Errorf("failed to parse ephemeral public key")
	}

	// Derive shared secret using ECDH (manual for ECDSA)
	sharedX, _ := k.curve.ScalarMult(ephemeralPubX, ephemeralPubY, privKey.D.Bytes())
	sharedSecret := sharedX.Bytes()

	// Derive symmetric key from shared secret
	ephemeralPub := &ecdsa.PublicKey{
		Curve: k.curve,
		X:     ephemeralPubX,
		Y:     ephemeralPubY,
	}
	symKey := k.deriveSymmetricKey(sharedSecret, ephemeralPub)

	// Parse nonce and ciphertext
	nonceLen := 12 // GCM nonce size
	if len(encryptedKey) < pubKeyLen+nonceLen {
		clearBytes(symKey)
		clearBytes(sharedSecret)
		return nil, fmt.Errorf("invalid encrypted key format: missing nonce")
	}

	nonce := encryptedKey[pubKeyLen : pubKeyLen+nonceLen]
	ciphertext := encryptedKey[pubKeyLen+nonceLen:]

	// Decrypt with symmetric key
	block, err := aes.NewCipher(symKey)
	if err != nil {
		clearBytes(symKey)
		clearBytes(sharedSecret)
		return nil, fmt.Errorf("failed to create cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		clearBytes(symKey)
		clearBytes(sharedSecret)
		return nil, fmt.Errorf("failed to create GCM: %w", err)
	}

	dek, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		clearBytes(symKey)
		clearBytes(sharedSecret)
		return nil, fmt.Errorf("failed to decrypt DEK: %w", err)
	}

	// Clear sensitive data
	clearBytes(symKey)
	clearBytes(sharedSecret)

	return dek, nil
}

// encryptDEKWithSessionKey encrypts DEK using session key
func (k *KeyUnwrapService) encryptDEKWithSessionKey(dek, sessionKey []byte) (*services.ECDHEncryptedDEK, error) {
	block, err := aes.NewCipher(sessionKey)
	if err != nil {
		return nil, fmt.Errorf("failed to create cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create GCM: %w", err)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("failed to generate nonce: %w", err)
	}

	ciphertext := gcm.Seal(nil, nonce, dek, nil)

	return &services.ECDHEncryptedDEK{
		Ciphertext: ciphertext,
		Nonce:      nonce,
	}, nil
}

// deriveSymmetricKey derives symmetric key from shared secret for ECIES
func (k *KeyUnwrapService) deriveSymmetricKey(sharedSecret []byte, ephemeralPub *ecdsa.PublicKey) []byte {
	info := elliptic.Marshal(k.curve, ephemeralPub.X, ephemeralPub.Y)
	return hkdfDerive(sharedSecret, nil, info, 32)
}

// deriveSessionKey derives session key from ECDH shared secret
func (k *KeyUnwrapService) deriveSessionKey(sharedSecret, serverPub, clientPub []byte) []byte {
	info := append(serverPub, clientPub...)
	return hkdfDerive(sharedSecret, nil, info, 32)
}

// hkdfDerive derives a key using HKDF
func hkdfDerive(secret, salt, info []byte, keyLen int) []byte {
	reader := hkdf.New(sha256.New, secret, salt, info)
	key := make([]byte, keyLen)
	io.ReadFull(reader, key)
	return key
}

// clearBytes clears a byte slice
func clearBytes(b []byte) {
	for i := range b {
		b[i] = 0
	}
}

// logAudit logs an audit entry
func (k *KeyUnwrapService) logAudit(operation, keyID, tokenID, userID, bucket, objectKey, result string) {
	k.auditLog.mu.Lock()
	defer k.auditLog.mu.Unlock()

	entry := AuditEntry{
		Timestamp: time.Now(),
		Operation: operation,
		KeyID:     keyID,
		TokenID:   tokenID,
		UserID:    userID,
		Bucket:    bucket,
		ObjectKey: objectKey,
		Result:    result,
	}

	k.auditLog.entries = append(k.auditLog.entries, entry)

	if len(k.auditLog.entries) > k.auditLog.maxSize {
		k.auditLog.entries = k.auditLog.entries[len(k.auditLog.entries)-k.auditLog.maxSize:]
	}
}

// Close cleans up the service
func (k *KeyUnwrapService) Close() error {
	k.mu.Lock()
	defer k.mu.Unlock()

	// Clear private key
	if k.decryptPrivKey != nil {
		for i := range k.decryptPrivKey.D.Bytes() {
			k.decryptPrivKey.D.Bytes()[i] = 0
		}
	}

	return nil
}
