// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: keygen.proto

package keygen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyGenService_GenerateDataKey_FullMethodName = "/nexus.keygen.KeyGenService/GenerateDataKey"
	KeyGenService_GetPublicKey_FullMethodName    = "/nexus.keygen.KeyGenService/GetPublicKey"
	KeyGenService_Health_FullMethodName          = "/nexus.keygen.KeyGenService/Health"
)

// KeyGenServiceClient is the client API for KeyGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyGenServiceClient interface {
	// Generate a new data encryption key
	// Returns encrypted DEK (for storage) and ECDH-encrypted DEK (for EncryptService)
	GenerateDataKey(ctx context.Context, in *GenerateDataKeyRequest, opts ...grpc.CallOption) (*GenerateDataKeyResponse, error)
	// Get service ECDH public key for key exchange
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type keyGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyGenServiceClient(cc grpc.ClientConnInterface) KeyGenServiceClient {
	return &keyGenServiceClient{cc}
}

func (c *keyGenServiceClient) GenerateDataKey(ctx context.Context, in *GenerateDataKeyRequest, opts ...grpc.CallOption) (*GenerateDataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDataKeyResponse)
	err := c.cc.Invoke(ctx, KeyGenService_GenerateDataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyGenServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, KeyGenService_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyGenServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, KeyGenService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyGenServiceServer is the server API for KeyGenService service.
// All implementations must embed UnimplementedKeyGenServiceServer
// for forward compatibility.
type KeyGenServiceServer interface {
	// Generate a new data encryption key
	// Returns encrypted DEK (for storage) and ECDH-encrypted DEK (for EncryptService)
	GenerateDataKey(context.Context, *GenerateDataKeyRequest) (*GenerateDataKeyResponse, error)
	// Get service ECDH public key for key exchange
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedKeyGenServiceServer()
}

// UnimplementedKeyGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyGenServiceServer struct{}

func (UnimplementedKeyGenServiceServer) GenerateDataKey(context.Context, *GenerateDataKeyRequest) (*GenerateDataKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDataKey not implemented")
}
func (UnimplementedKeyGenServiceServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedKeyGenServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKeyGenServiceServer) mustEmbedUnimplementedKeyGenServiceServer() {}
func (UnimplementedKeyGenServiceServer) testEmbeddedByValue()                       {}

// UnsafeKeyGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyGenServiceServer will
// result in compilation errors.
type UnsafeKeyGenServiceServer interface {
	mustEmbedUnimplementedKeyGenServiceServer()
}

func RegisterKeyGenServiceServer(s grpc.ServiceRegistrar, srv KeyGenServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyGenService_ServiceDesc, srv)
}

func _KeyGenService_GenerateDataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenServiceServer).GenerateDataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyGenService_GenerateDataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenServiceServer).GenerateDataKey(ctx, req.(*GenerateDataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyGenService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyGenService_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyGenService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyGenService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyGenService_ServiceDesc is the grpc.ServiceDesc for KeyGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.keygen.KeyGenService",
	HandlerType: (*KeyGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDataKey",
			Handler:    _KeyGenService_GenerateDataKey_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _KeyGenService_GetPublicKey_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _KeyGenService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keygen.proto",
}
