// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: keygen.proto

package keygen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "nexus/proto/common"
	_ "nexus/proto/token"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateDataKeyRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *common.DelegationToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                        // Must be WRITE token
	ClientEcdhPub *common.ECDHPublicKey   `protobuf:"bytes,2,opt,name=client_ecdh_pub,json=clientEcdhPub,proto3" json:"client_ecdh_pub,omitempty"` // Client's ECDH public key for session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDataKeyRequest) Reset() {
	*x = GenerateDataKeyRequest{}
	mi := &file_keygen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDataKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDataKeyRequest) ProtoMessage() {}

func (x *GenerateDataKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDataKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateDataKeyRequest) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDataKeyRequest) GetToken() *common.DelegationToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *GenerateDataKeyRequest) GetClientEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ClientEcdhPub
	}
	return nil
}

type GenerateDataKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEK encrypted with service's long-term public key (for KeyStore)
	EncryptedDek *common.EncryptedDEK `protobuf:"bytes,1,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"`
	// DEK encrypted with ECDH-derived session key (for EncryptService)
	EcdhEncryptedDek *common.ECDHEncryptedDEK `protobuf:"bytes,2,opt,name=ecdh_encrypted_dek,json=ecdhEncryptedDek,proto3" json:"ecdh_encrypted_dek,omitempty"`
	// Service's ephemeral ECDH public key (for client to derive shared secret)
	ServiceEcdhPub *common.ECDHPublicKey `protobuf:"bytes,3,opt,name=service_ecdh_pub,json=serviceEcdhPub,proto3" json:"service_ecdh_pub,omitempty"`
	// Key metadata
	KeyId         string        `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     string        `protobuf:"bytes,5,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // e.g., "AES-256-GCM"
	Error         *common.Error `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDataKeyResponse) Reset() {
	*x = GenerateDataKeyResponse{}
	mi := &file_keygen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDataKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDataKeyResponse) ProtoMessage() {}

func (x *GenerateDataKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDataKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateDataKeyResponse) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDataKeyResponse) GetEncryptedDek() *common.EncryptedDEK {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *GenerateDataKeyResponse) GetEcdhEncryptedDek() *common.ECDHEncryptedDEK {
	if x != nil {
		return x.EcdhEncryptedDek
	}
	return nil
}

func (x *GenerateDataKeyResponse) GetServiceEcdhPub() *common.ECDHPublicKey {
	if x != nil {
		return x.ServiceEcdhPub
	}
	return nil
}

func (x *GenerateDataKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GenerateDataKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GenerateDataKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_keygen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{2}
}

type GetPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service's long-term public key for encrypting DEK (RSA/ECIES)
	PublicKey     []byte        `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KeyId         string        `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     string        `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Error         *common.Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_keygen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetPublicKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetPublicKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GetPublicKeyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_keygen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_keygen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_keygen_proto protoreflect.FileDescriptor

const file_keygen_proto_rawDesc = "" +
	"\n" +
	"\fkeygen.proto\x12\fnexus.keygen\x1a\fcommon.proto\x1a\vtoken.proto\"\x92\x01\n" +
	"\x16GenerateDataKeyRequest\x123\n" +
	"\x05token\x18\x01 \x01(\v2\x1d.nexus.common.DelegationTokenR\x05token\x12C\n" +
	"\x0fclient_ecdh_pub\x18\x02 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\rclientEcdhPub\"\xcf\x02\n" +
	"\x17GenerateDataKeyResponse\x12?\n" +
	"\rencrypted_dek\x18\x01 \x01(\v2\x1a.nexus.common.EncryptedDEKR\fencryptedDek\x12L\n" +
	"\x12ecdh_encrypted_dek\x18\x02 \x01(\v2\x1e.nexus.common.ECDHEncryptedDEKR\x10ecdhEncryptedDek\x12E\n" +
	"\x10service_ecdh_pub\x18\x03 \x01(\v2\x1b.nexus.common.ECDHPublicKeyR\x0eserviceEcdhPub\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x05 \x01(\tR\talgorithm\x12)\n" +
	"\x05error\x18\x06 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\x15\n" +
	"\x13GetPublicKeyRequest\"\x95\x01\n" +
	"\x14GetPublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x13.nexus.common.ErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\x8b\x02\n" +
	"\rKeyGenService\x12^\n" +
	"\x0fGenerateDataKey\x12$.nexus.keygen.GenerateDataKeyRequest\x1a%.nexus.keygen.GenerateDataKeyResponse\x12U\n" +
	"\fGetPublicKey\x12!.nexus.keygen.GetPublicKeyRequest\x1a\".nexus.keygen.GetPublicKeyResponse\x12C\n" +
	"\x06Health\x12\x1b.nexus.keygen.HealthRequest\x1a\x1c.nexus.keygen.HealthResponseB\x14Z\x12nexus/proto/keygenb\x06proto3"

var (
	file_keygen_proto_rawDescOnce sync.Once
	file_keygen_proto_rawDescData []byte
)

func file_keygen_proto_rawDescGZIP() []byte {
	file_keygen_proto_rawDescOnce.Do(func() {
		file_keygen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keygen_proto_rawDesc), len(file_keygen_proto_rawDesc)))
	})
	return file_keygen_proto_rawDescData
}

var file_keygen_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_keygen_proto_goTypes = []any{
	(*GenerateDataKeyRequest)(nil),  // 0: nexus.keygen.GenerateDataKeyRequest
	(*GenerateDataKeyResponse)(nil), // 1: nexus.keygen.GenerateDataKeyResponse
	(*GetPublicKeyRequest)(nil),     // 2: nexus.keygen.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),    // 3: nexus.keygen.GetPublicKeyResponse
	(*HealthRequest)(nil),           // 4: nexus.keygen.HealthRequest
	(*HealthResponse)(nil),          // 5: nexus.keygen.HealthResponse
	(*common.DelegationToken)(nil),  // 6: nexus.common.DelegationToken
	(*common.ECDHPublicKey)(nil),    // 7: nexus.common.ECDHPublicKey
	(*common.EncryptedDEK)(nil),     // 8: nexus.common.EncryptedDEK
	(*common.ECDHEncryptedDEK)(nil), // 9: nexus.common.ECDHEncryptedDEK
	(*common.Error)(nil),            // 10: nexus.common.Error
}
var file_keygen_proto_depIdxs = []int32{
	6,  // 0: nexus.keygen.GenerateDataKeyRequest.token:type_name -> nexus.common.DelegationToken
	7,  // 1: nexus.keygen.GenerateDataKeyRequest.client_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	8,  // 2: nexus.keygen.GenerateDataKeyResponse.encrypted_dek:type_name -> nexus.common.EncryptedDEK
	9,  // 3: nexus.keygen.GenerateDataKeyResponse.ecdh_encrypted_dek:type_name -> nexus.common.ECDHEncryptedDEK
	7,  // 4: nexus.keygen.GenerateDataKeyResponse.service_ecdh_pub:type_name -> nexus.common.ECDHPublicKey
	10, // 5: nexus.keygen.GenerateDataKeyResponse.error:type_name -> nexus.common.Error
	10, // 6: nexus.keygen.GetPublicKeyResponse.error:type_name -> nexus.common.Error
	0,  // 7: nexus.keygen.KeyGenService.GenerateDataKey:input_type -> nexus.keygen.GenerateDataKeyRequest
	2,  // 8: nexus.keygen.KeyGenService.GetPublicKey:input_type -> nexus.keygen.GetPublicKeyRequest
	4,  // 9: nexus.keygen.KeyGenService.Health:input_type -> nexus.keygen.HealthRequest
	1,  // 10: nexus.keygen.KeyGenService.GenerateDataKey:output_type -> nexus.keygen.GenerateDataKeyResponse
	3,  // 11: nexus.keygen.KeyGenService.GetPublicKey:output_type -> nexus.keygen.GetPublicKeyResponse
	5,  // 12: nexus.keygen.KeyGenService.Health:output_type -> nexus.keygen.HealthResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_keygen_proto_init() }
func file_keygen_proto_init() {
	if File_keygen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keygen_proto_rawDesc), len(file_keygen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keygen_proto_goTypes,
		DependencyIndexes: file_keygen_proto_depIdxs,
		MessageInfos:      file_keygen_proto_msgTypes,
	}.Build()
	File_keygen_proto = out.File
	file_keygen_proto_goTypes = nil
	file_keygen_proto_depIdxs = nil
}
